### PR TITLE
Manage CI deps with pip-compile-multi

### PR DESCRIPTION
**Pull request by richardsheridan**
This is just a bit of a goof right now, but it could be a way to ditch dependabot if necessary. The PR only exists to check if I got the CI settings right

### CODE REVIEW

**Comment by richardsheridan** [comment]
Looks like it'll work except for managing py36 versions, so defer this until at least when we drop 36 support

**Comment by belm0** [comment]
>  it could be a way to ditch dependabot if necessary

@richardsheridan Please, yes.  I've ranted on trio gitter recently, but again I saw it starkly when visiting the trio-parallel repo today:  dependabot has disinvented git.  I used to be able to visit any repo and in a minute assess the activity and health of the project, regardless of whether the maintainer keeps an accurate changelog (including pre-release changes), etc.  But now git history for a modest project like this one is overwhelmed with administrative commits, and I can't see what's going on.

(You probably know, but the specific package versions used by a library's CI tests have no bearing on security for end users of the library, so Dependabot is just silliness outside of an application context.)

I don't know if pip-compile-multi is the best.  For my personal and work projects just pip-compile and some refined makefile targets works well.  The lack of obscure layers has been refreshing (formerly I lived the nightmare of using pipenv), and I haven't looked back.

Let me know if I can help at all-- and please spread the word.

**Comment by richardsheridan** [comment]
Thanks for commenting! As this project's top user, that carries a lot of weight.

I started using dependabot to follow trio. But as you say, I only need periodic but automated updates and some more frequent, unpinned check that `pip install trio-parallel && pytest --pyargs trio-parallel` works.

I'm not dead set on pip-compile-multi but makefile and gha workflows are similarly obscure layers from my perspective.

If you could point me to an example of a system that periodically opens issues and PRs but with minimal complexity I would appreciate it!

**Comment by belm0** [comment]
> periodically opens issues and PRs

I haven't found a need to automate this.

Assuming you have a github trigger set up to make the unpinned build periodically, when that fails that will be the hard signal that it's time to review dependencies.  Otherwise there isn't much urgency, and upgrading test/dev dependencies ad-hoc when you have the itch seems to work fine.

The makefile target I use for dependency management is just a few lines, and more documentation than code:

```Makefile
# NOTE: In CI builds, the requirements .txt files should already reflect .in,
# setup.py, and other dependencies.  Generation or updating of .txt files must be
# explicitly requested by the developer using the `requirements` target, and
# not executed during CI.
#
# To change requirements, edit the *.in or setup.py files as necessary, then:
#     make requirements
# To upgrade a specific pinned package (e.g. trio-util of dev-requirements.txt):
#     make -B dev-requirements.txt PIP_COMPILE_ARGS="-P trio-util"
#     make requirements
# To upgrade all pinned packages (e.g. of dev-requirements.txt):
#     make -B dev-requirements.txt PIP_COMPILE_ARGS="-U"
#     make requirements

.PHONY: requirements
requirements:

ifneq (,$(filter $(MAKECMDGOALS),requirements dev-requirements.txt))
dev-requirements.txt: dev-requirements.in setup.py
	pip-compile -q $(PIP_COMPILE_ARGS) --output-file $@ $^
endif

ifneq (,$(filter $(MAKECMDGOALS),requirements other-requirements.txt))
other-requirements.txt: other-requirements.in dev-requirements.txt
	pip-compile -q $(PIP_COMPILE_ARGS) --output-file $@ $^
endif
```

**Pull request merged**
